condition:
     - case
     - control

microbeannotator_db_path: "/mnt/scratch/LM/KMER/MicrobeAnnotator_DB/"
kraken_database_path: "/mnt/software/dataset/db/kraken2/2022/"
src_path: "/path/to/META-DIFF/"
project_path: "/mnt/ssd/LM/"
fof: "/mnt/projects_tn03/KMER_analysis/DATA/AcneData/fof.txt"

experiment_name: "microbiome_analysis"
threads: 120
unitig_length: 500
bcalm_memory: 20000
partitions: 8
bitw: 8
bloom_filter: 1000000000
top_unitigs: 5000
neptune_key: ""
log_neptune: 0
n_splits: 5
n_calls: 20