condition:
     - case
     - control

microbeannotator_db_path: "/mnt/scratch/LM/KMER/MicrobeAnnotator_DB/"
kraken_database_path: "/mnt/scratch/LM/KMER/ncbi_database/NCBI_ALL_DB"
src_path: "/path/to/META-DIFF/"
project_path: "/mnt/ssd/LM/"
fof: "/mnt/projects_tn03/KMER_analysis/DATA/AcneData/fof.txt"

threads: 120
unitig_length: 500
bcalm_memory: 20000
partitions: 8
