resources:
     mmseqs:
          mem: 300 # Go

microbeannotator_db_path: /path/to/db
taxonomic_db_path: /path/to/db
seq_to_genome: /path/to/ref
seq_to_species: /path/to/retailed_ref
src_path: /path/to/META-DIFF/
project_path: /path/to/your/project/
fof: /path/to/your/file_of_file.txt


