resources:
     mmseqs:
          mem: 300 # Go

condition:
     - case
     - control

microbeannotator_db_path: "/mnt/scratch/LM/KMER/MicrobeAnnotator_DB/"
taxonomic_db_path: "/mnt/scratch/LM/KMER/ncbi_database/NCBI_ALL_DB"
seq_to_genomes: "/home/guelou01/seqid_in_all_seq.fna.txt"
seq_to_species: "/home/guelou01/seqid_in_all_seq.fna_simplified_.txt"
src_path: "/mnt/projects_tn03/KMER_analysis/META-DIFF/"
project_path: "/mnt/ssd/LM/"
fof: "/mnt/projects_tn03/KMER_analysis/META-DIFF/fof.txt"

threads: 120
unitig_length: 1000
bcalm_memory: 20000
