resources:
     mmseqs:
          mem: 300 # Go

microbeannotator_db_path: /mnt/scratch/LM/KMER/MicrobeAnnotator_DB/
taxonomic_db_path: /mnt/scratch/LM/KMER/NCBI/
seq_to_genome: /mnt/home/guelou01/
seq_to_species: /mnt/home/guelou01/
src_path: /mnt/projects_tn03/KMER_analysis/META-DIFF/
project_path: /path/to/project
fof: /path/to/your/file_of_file.txt


